Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-3, pull requests merged in 2025-08, with the labels that each got.

#25 [Chore] 기본 routerProvider 설정
  package-lock.json
  package.json
  src/App.tsx
  src/pages/index.tsx
  src/router/index.tsx
  src/router/routes.tsx
  tsconfig.app.json
Labels: done

#30 style/ Header, Footer
  package.json
  public/icon/test.svg
  public/image/Logo-Black.png
  public/image/Logo.png
  public/image/github.png
  public/image/programmers.png
  public/image/test.svg
  src/App.tsx
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/index.tsx
  src/main.tsx
  src/pages/index.tsx
  src/router/routes.tsx
  src/styles/style.css
Labels: done

#28 [Style] 공통 Scroll 스타일 설정
  .gitignore
  index.html
  public/icon/fi-rr-glass-cheers.svg
  public/image/favicon.svg
  src/component/Header.tsx
  src/pages/MyPage/MyPageLayout.tsx
  src/router/routes.tsx
  src/styles/style.css
Labels: done

#43 [Feat] 공통 Spinner, Button Component 생성
  package-lock.json
  package.json
  src/component/Button.tsx
  src/component/Spinner.tsx
  src/pages/MyPage/MyPageLayout.tsx
  src/styles/style.css
  src/utils/index.tsx
  src/utils/tw.ts
Labels: done

#44 Feature/community write cs
  src/component/Header.tsx
  src/pages/community/write/CommunityWrite.tsx
  src/pages/community/write/LeftContent.tsx
  src/pages/community/write/RightPreview.tsx
  src/router/index.tsx
  src/router/routes.tsx
Labels: feature

#46 [Chore] Data Crawling Test Result
  src/data/data.json
  src/data/index.tsx
  src/router/routes.tsx
Labels: inProgress

#48 Style/로그인,회원가입
  public/icon/email.svg
  public/icon/fi-rr-glass-cheers.png
  public/icon/fi-rr-glass-cheers.svg
  public/icon/password.svg
  public/icon/profileIcon.svg
  public/icon/unvisible.svg
  public/icon/visible.svg
  public/image/loginImg.png
  public/image/registerImg.png
  src/component/Header.tsx
  src/data/data.json
  src/pages/Login/Login.tsx
  src/pages/Login/Register.tsx
  src/pages/MainPage/Collection.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/MainPagination.tsx
  src/pages/index.tsx
  src/router/routes.tsx
Labels: done

#50 [Feat] MyPage / NavList 개발
  package-lock.json
  package.json
  src/@types/global.d.ts
  src/assets/MyPageIcon/achievement-black.svg
  src/assets/MyPageIcon/achievement.svg
  src/assets/MyPageIcon/activity-black.svg
  src/assets/MyPageIcon/activity.svg
  src/assets/MyPageIcon/home-black.svg
  src/assets/MyPageIcon/home.svg
  src/assets/MyPageIcon/settings-black.svg
  src/assets/MyPageIcon/settings.svg
  src/assets/MyPageIcon/wine-seller-black.svg
  src/assets/MyPageIcon/wine-seller.svg
  src/assets/MyPageIcon/wish-list-black.svg
  src/assets/MyPageIcon/wish-list.svg
  src/component/Header.tsx
  src/component/MyPage/MyPageNav.tsx
  src/component/MyPage/NavIcons.ts
  src/component/MyPage/SettingImage.tsx
  src/component/MyPage/settingErrorCodes.ts
  src/hook/index.tsx
  src/hook/useProfileSettingError.ts
  src/pages/MyPage/MyAchievement.tsx
  src/pages/MyPage/MyActivities.tsx
  src/pages/MyPage/MyHome.tsx
  src/pages/MyPage/MyPageLayout.tsx
  src/pages/MyPage/Settings.tsx
  src/pages/MyPage/WineSeller.tsx
  src/pages/MyPage/WishList.tsx
  src/router/index.tsx
  src/router/routes.tsx
  src/utils/extractNavItems.ts
  src/utils/joinPath.ts
  src/utils/supabase/uploadImage.ts
  vite.config.ts
Labels: inProgress

#55 Feat/헤더 서치바
  package-lock.json
  package.json
  public/icon/champaignIcon.png
  public/icon/dessertWineIcon.png
  public/icon/redWineIcon.png
  public/icon/roseWineIcon.png
  public/icon/search-btn.svg
  public/icon/whitewineIcon.png
  src/component/Header.tsx
  src/component/HeaderSearchSection.tsx
  src/component/Login/VisibleBtn.tsx
  src/component/MainPage/Categories.tsx
  src/component/MainPage/Collection.tsx
  src/component/MainPage/MainPagination.tsx
  src/component/MainPage/ShowMoreBtn.tsx
  src/component/MainPage/UserCollection.tsx
  src/component/MainPage/WineGrid.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/Register.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/community/store/useCommunityStore.ts
  src/pages/community/write/CommunityWrite.tsx
  src/pages/community/write/RightPreview.tsx
  src/utils/extractNavItems.ts
  src/utils/joinPath.ts
Labels: inProgress

#59 Feat/404page
  public/image/404image.png
  src/pages/Page404.tsx
  src/router/routes.tsx
Labels: done

#61 feat/ search바 렌더링 오류 해결
  src/component/Header.tsx
  src/component/HeaderSearchSection.tsx
Labels: bug

#66 [Feat] MyPage Setting - Supabase 함수 연결
  src/@types/global.d.ts
  src/component/ConfirmModal.tsx
  src/component/MyPage/ChangePasswordModal.tsx
  src/component/MyPage/PhoneInput.tsx
  src/component/MyPage/SettingAccount.tsx
  src/component/MyPage/SettingImage.tsx
  src/component/MyPage/SettingPersonalInfo.tsx
  src/hook/useConfirm.ts
  src/main.tsx
  src/store/@store.ts
  src/supabase/database.types.ts
  src/utils/formatPhoneNumber.ts
  src/utils/supabase/changePassword.ts
  src/utils/supabase/unregister.ts
  src/utils/supabase/upsertTable.ts
Labels: inProgress
