Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-3, pull requests merged in 2025-09, with the labels that each got.

#73 [Feat] 댓글 대댓글 CRUD
  src/@types/global.d.ts
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/HeaderSearchSection.tsx
  src/hook/fetch.ts
  src/hook/useKeyDown.ts
  src/hook/useTimer.ts
  src/pages/community/detail/CommentReply.tsx
  src/pages/community/detail/CommunityDetail.tsx
  src/pages/community/detail/InputComment..tsx
  src/pages/community/detail/PostComment.tsx
  src/pages/community/write/LeftContent.tsx
  src/pages/community/write/store/useCommunityStore.ts
  src/pages/index.tsx
  src/supabase/community/communityCreate.ts
  src/utils/supabase/fetch.ts
Labels: done

#75 Feat/login시 user이미지 들어오는기능
  src/component/Header.tsx
  src/pages/Login/FindPassword.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/Register.tsx
  src/router/routes.tsx
  src/store/@store.ts
Labels: inProgress

#76 Feat/검색결과창 제작
  src/assets/staticArr.ts
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/MainPage/Categories.tsx
  src/component/MainPage/Collection.tsx
  src/component/MainPage/MainSearchBar.tsx
  src/component/MainPage/WineGrid.tsx
  src/component/search/HeaderSearchSection.tsx
  src/component/search/Items.tsx
  src/hook/ScrolToTop.ts
  src/hook/fetch.ts
  src/hook/useFilter.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/SearchResult.tsx
  src/pages/index.tsx
  src/router/routes.tsx
  src/supabase/database.types.ts
Labels: inProgress

#81 Feat/MyPage Settings Supabase 테이블 연결
  package-lock.json
  package.json
  src/component/MyPage/MyPageNav.tsx
  src/component/MyPage/SettingBio.tsx
  src/component/MyPage/SettingImage.tsx
  src/component/MyPage/SettingPersonalInfo.tsx
  src/component/MyPage/profileErrorCodes.ts
  src/hook/profileSetting/useProfileBasic.ts
  src/hook/profileSetting/useProfileBio.ts
  src/hook/profileSetting/useProfileInfo.ts
  src/hook/profileSetting/useProfileSettingError.ts
  src/main.tsx
  src/supabase/database.types.ts
  src/utils/supabase/upsertTable.ts
Labels: done

#92 Feat/MyPage Wine Seller, Wish List 추가
  package-lock.json
  package.json
  public/icon/bookmark.svg
  public/icon/bookmarkFilled.svg
  src/component/MyPage/WineSeller/AddNewCard.tsx
  src/component/MyPage/WineSeller/WineAnalysisPie.tsx
  src/component/MyPage/WineSeller/WineRatingDistBar.tsx
  src/component/MyPage/WineSeller/WineSellerCard.tsx
  src/component/MyPage/WineSeller/WineSellerCardSkeleton.tsx
  src/component/MyPage/WineSeller/WineTasteAnalysis.tsx
  src/component/MyPage/WineWishCard.tsx
  src/hook/myPage/useMyReviewAgg.ts
  src/hook/myPage/useMyReviews.ts
  src/hook/myPage/useWishList.ts
  src/pages/MyPage/WineSeller.tsx
  src/pages/MyPage/WishList.tsx
Labels: inProgress

#95 Feat/검색결과창 페이지네이션
  public/icon/flavor/aging.svg
  public/icon/flavor/apple.svg
  public/icon/flavor/chocolate.svg
  public/icon/flavor/citrus.svg
  public/icon/flavor/dessert.svg
  public/icon/flavor/driedfruit.svg
  public/icon/flavor/grape.svg
  public/icon/flavor/nut.svg
  public/icon/flavor/stoneFruit.svg
  public/icon/flavor/sweet.svg
  public/image/mobileHeroImg.png
  public/image/mobileHeroText.png
  src/assets/staticArr.ts
  src/component/Footer.tsx
  src/component/Header.tsx
  src/component/MainPage/AnimatedPost.tsx
  src/component/MainPage/Collection.tsx
  src/component/MainPage/ShowMoreBtn.tsx
  src/component/MainPage/UserCollection.tsx
  src/component/search/HeaderSearchSection.tsx
  src/component/search/skeleton/MainSearchBarSkeleton.tsx
  src/component/search/skeleton/SearchResultSkeleton.tsx
  src/component/search/skeleton/SkeletonItem.tsx
  src/component/wine/wineInfo/matchFlavor.ts
  src/hook/useEditPost.ts
  src/hook/useFilter.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/SearchResult.tsx
  src/pages/community/Main/Card.tsx
  src/pages/community/detail/CommunityDetail.tsx
  src/pages/community/detail/InputComment..tsx
  src/pages/community/detail/PostComment.tsx
  src/pages/index.tsx
  src/router/routes.tsx
  src/styles/style.css
  src/supabase/database.types.ts
Labels: done

#109 Feat/mainpage QA에러 수정
  index.html
  package-lock.json
  package.json
  public/image/Logo.png
  public/image/favicon.png
  public/image/favicon.svg
  src/App.tsx
  src/component/Header.tsx
  src/component/MainPage/Collection.tsx
  src/component/MainPage/ShowMoreBtn.tsx
  src/component/MainPage/UserCollection.tsx
  src/component/search/HeaderSearchSection.tsx
  src/component/search/MainSearchBar.tsx
  src/hook/fetch.ts
  src/hook/search/useSearch.ts
  src/hook/useEditPost.ts
  src/pages/Login/FindEmail.tsx
  src/pages/Login/FindPassword.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/Register.tsx
  src/pages/Login/ResetPassword.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/SearchResult.tsx
  src/pages/community/detail/CommunityDetail.tsx
  src/pages/community/write/LeftContent.tsx
  src/store/@store.ts
  src/store/searchStore.ts
  src/supabase/community/uploadImages.ts
Labels: bug

#113 Fix/bug Find Email 함수 구현
  .gitignore
  src/pages/Login/FindEmail.tsx
  src/utils/supabase/findEmailByPhone.ts
  supabase/config.toml
  supabase/functions/find-email/.npmrc
  supabase/functions/find-email/deno.json
  supabase/functions/find-email/index.ts
Labels: inProgress, feature

#115 fix/ DB전화번호 인서트 수정
  src/App.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/Register.tsx
  src/pages/SearchResult.tsx
Labels: bug

#120 Feat/로그인 로그아웃 픽스
  src/component/MyPage/WineSeller/WineRatingDistBar.tsx
  src/hook/confirmFunction.ts
  src/hook/myPage/useMyReviews.ts
  src/pages/Login/Login.tsx
  src/pages/community/detail/PostComment.tsx
  src/store/@store.ts
Labels: bug

#121 fix/ 로그인시 경로 수정 및 confirmUI
  src/hook/confirmFunction.ts
  src/pages/Login/Login.tsx
  src/pages/Login/ResetPassword.tsx
  src/store/@store.ts
Labels: bug

#125 Feat/MyPage Wine Seller 에서 Review 수정할 수 있도록 변경
  src/component/Header.tsx
  src/component/MyPage/WineSeller/WineSellerCard.tsx
  src/component/community/TextEditor.tsx
  src/component/wine/wineDetailInfo/wineReview/Review.tsx
  src/component/wine/wineDetailInfo/wineReview/ReviewModal.tsx
  src/hook/myPage/useMyReviews.ts
  src/hook/useFilter.ts
  src/pages/MyPage/MyHome.tsx
  src/pages/MyPage/WineSeller.tsx
  src/pages/community/detail/CommentReply.tsx
  src/pages/community/detail/PostComment.tsx
  src/pages/supabaseTest/TestSupabase.tsx
  src/pages/wine/WineDetails.tsx
  src/pages/wine/Wines.tsx
  src/store/reviewStore.ts
Labels: inProgress

#126 fix/.wine페이지 진입시 콘솔에러 fix
  src/component/MainPage/Collection.tsx
  src/component/wine/filterSearch/filterInfo.ts
  src/pages/Login/Login.tsx
  src/pages/Login/ResetPassword.tsx
  src/supabase/supabase.ts
Labels: bug
